=== EriJGS/XML_Esquemas/Songs.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/Songs.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE playlist SYSTEM "Songs.dtd">

    <playlist>
    ...
    </playlist>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT playlist (cancion)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cancion (duracion|anio|titulo|compositor|productor|sello|artista)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT duracion (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT anio (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT titulo (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT compositor (nombre, apellido)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nombre (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT apellido (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT productor (nombre, apellido)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sello (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT artista (#PCDATA)>

=== EriJGS/XML_Esquemas/Songs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!-- <!DOCTYPE playlist SYSTEM "Songs.dtd"> -->

<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:SchemaLocation="Songs.xsd">
    <cancion>
        <duracion>4.47</duracion>
        <anio>2008</anio>
        <titulo>Give it 2 me</titulo>
        <compositor>
            <nombre>Pharrell</nombre>
            <apellido>Williams</apellido>
        </compositor>
        <productor>
            <nombre>Pharrell</nombre>
            <apellido>Williams</apellido>
        </productor>
        <sello>Warner Bros, Records</sello>
        <artista>Madonna</artista>
    </cancion>
    
    <cancion>
        <duracion>5.07</duracion>
        <anio>2011</anio>
        <titulo>Ode to Sleep</titulo>
        <compositor>
            <nombre>Tyler</nombre>
            <apellido>Joseph</apellido>
        </compositor>
        <productor>
            <nombre>Greg</nombre>
            <apellido>Wells</apellido>
        </productor>
        <sello>Fueled by Ramen</sello>
        <artista>Twenty One Pilots</artista>
    </cancion>
    
    <cancion>
        <duracion>5.55</duracion>
        <anio>1975</anio>
        <titulo>Bohemian Rhapsody</titulo>
        <compositor>
            <nombre>Freddie</nombre>
            <apellido>Mercury</apellido>
        </compositor>
        <productor>
            <nombre>Roy</nombre>
            <apellido>Baker</apellido>
        </productor>
        <sello>EMI</sello>
        <sello>Elektra Records</sello>
        <sello>Parlophone</sello>
        <sello>Hollywood Records</sello>
        <artista>Queen</artista>
    </cancion>
    
</playlist>
